// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"database/sql"
	"time"
)

type Task struct {
	TaskID    string
	CreatedAt time.Time
}

type TaskLog struct {
	TaskLogID   string
	TaskID      string
	Title       string
	Description sql.NullString
	Done        int64
	Deadline    sql.NullTime
	CreatedAt   time.Time
}
