query AllTasks {
  tasks {
    taskId
    taskLogId
    title
    detail
    done
    deadline
  }
}

mutation UpdateTask(
  $taskId: ID!
  $title: String
  $detail: String
  $done: Boolean
  $deadline: Time
) {
  updateTask(
    input: {
      taskId: $taskId
      title: $title
      detail: $detail
      done: $done
      deadline: $deadline
    }
  ) {
    taskId
    taskLogId
    title
    detail
    done
    deadline
  }
}

mutation SyncTasks($tasks: SyncTasks!) {
  syncTasks(input: $tasks) {
    taskId
    taskLogId
    title
    detail
    done
    deadline
  }
}
