query AllTasks {
  tasks {
    taskId
    taskLogId
    title
    detail
    done
    deadline
  }
}

mutation SyncTasks($tasks: SyncTasks!) {
  syncTasks(input: $tasks) {
    taskId
    taskLogId
    title
    detail
    done
    deadline
  }
}
