// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewTask struct {
	Title    string     `json:"title"`
	Detail   *string    `json:"detail"`
	Deadline *time.Time `json:"deadline"`
}

type SubTask struct {
	SubTaskID    string     `json:"subTaskId"`
	SubTaskLogID string     `json:"subTaskLogId"`
	Title        string     `json:"title"`
	Detail       *string    `json:"detail"`
	Done         bool       `json:"done"`
	Deadline     *time.Time `json:"deadline"`
}

type SyncTasks struct {
	NewTasks     []*NewTask     `json:"newTasks"`
	UpdatedTasks []*UpdatedTask `json:"updatedTasks"`
}

type UpdatedTask struct {
	TaskID   string     `json:"taskId"`
	Title    *string    `json:"title"`
	Detail   *string    `json:"detail"`
	Done     *bool      `json:"done"`
	Deadline *time.Time `json:"deadline"`
}
